### ISSUE TITLE
Security : XSS on Article (404)

### ISSUE THREAD

**Issue by omarkurt** [kjk/blog#27]
Hi @kjk, I review golang code for Learning. Look at this repo. 

https://blog.kowalczyk.info/article/test<script>alert("@omarkurt");</script>/searching-for-available-dba-name-in-san-francisco.html please open with Firefox!

I think vulnerable line : https://github.com/kjk/blog/blob/dc9432a804936d011f7a28b197b3b5d5acd40159/handler_mainpage.go#L43 

Reference : https://www.netsparker.com/blog/web-security/cross-site-scripting-xss/
Secure Coding for Golang : https://checkmarx.gitbooks.io/go-scp/output-encoding/cross-site-scripting.html 

Good luck!

**Comment by kjk** [comment]
Thanks for letting me know. Fixed with https://github.com/kjk/blog/commit/53b9d303b55351fecc6bf125e06fb1935e033fde
