### ISSUE TITLE
which go program?

### ISSUE THREAD

**Issue by luckypoem** [kjk/blog#28]
u said "It's generated mostly from markdown files by a simple Go program",
which go program are u referring to?

**Comment by kjk** [comment]
All the .go files in top directory like https://github.com/kjk/blog/blob/master/main.go

This is how .html files are generated: https://github.com/kjk/blog/blob/master/s/build.ps1

**Comment by luckypoem** [comment]
in $GOPATH, I RAN :  go get github.com/kjk/blog

it shows:
...
src/github.com/kjk/blog/gen_netlify.go:500:21: multiple-value uuid.NewV4() in single-value context
src/github.com/kjk/blog/notes.go:154:23: xurls.Relaxed.FindAllString undefined (type func() *regexp.Regexp has no field or method FindAllString)
root@ar:~/go/gopath# 

how to fix the errors?

**Comment by kjk** [comment]
Try:

go get -v -u github.com/golang/dep/cmd/dep
dep ensure -v

This makes sure the right version of all dependencies is used.
