### ISSUE TITLE
Multiple lines per log

### ISSUE THREAD

**Issue by fulldump** [kjk/blog#29]
Hi, I was reading your article https://github.com/kjk/blog/blob/master/books/go-cookbook/simple-serialization-for-logging-and-analytics.md and I like your requirements and your reasons discarding other alternatives:
> csv - efficient but uses fixed records and not very readable if there are many fields on a single line
> json - not very readable
> protocol buffers - binary so not human readable, needs up-front scheme

But how about loosing the benefits of having the same log information in one line?

**Comment by kjk** [comment]
Those are unfortunately conflicting requirements.

I had to pick one property so I picked ability to have (easy) structured (multi-value) logging over single-line logging.
